version: '3.3'

services:
  postgres:
    image: postgres
    container_name: dbpedidos
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    networks:
      - pedidos_default

  app:
    depends_on:
      - postgres
    build: ./
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRES_DOCKER_PORT/$POSTGRES_DATABASE",
        "spring.datasource.username" : "$POSTGRES_ROOT_USER",
        "spring.datasource.password" : "$POSTGRES_ROOT_PASSWORD",
        "spring.jpa.hibernate.show-sql" : true,
        "spring.datasource.initialization-mode" : "always",
        "spring.datasource.initialize" : true,
        "spring.datasource.continue-on-error": true,
        "spring.jpa.hibernate.ddl-auto":"update",
        "server.port" : "$SPRING_LOCAL_PORT",
        "server.servlet.context-path" : "/tech-challenge",
        "producao.service.url" : "http://localhost:9092/tech-challenge/producao",
        "pagamentos.service.url" : "http://localhost:9090/tech-challenge/pagamento",
        "feign.client.config.default.connectTimeout" : 14000,
        "feign.client.config.default.readTimeout" : 14000
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - pedidos_default

  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadminpedidos
    env_file: ./.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_ROOT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_ROOT_PASSWORD
    ports:
      - "8081:80"
    networks:
      - pedidos_default

networks:
  pedidos_default:
    driver: bridge
